### ISSUE TITLE
我想我在vscode 中是否可以启动前端这个项目

### ISSUE THREAD

**Issue by supercating** [codingtalk/tacomall#8]
我用 npm install  安装了插件，但当我运行npm run lint-fix 和 test 都未能成功

**Comment by supercating** [comment]
api 这个目录我找不到位置

**Comment by codingtalk** [comment]
需要在这个目录下，https://github.com/codingtalk/tacomall/tree/master/tacomall-ma，使用hbuilderx打开运行编译，再用vscode打开代码编辑
